package com.hxoms.modules.publicity.docCallback.mapper;

import com.hxoms.modules.publicity.docCallback.entity.OmsPubDoccallback;
import com.hxoms.modules.publicity.docCallback.entity.parameterEntity.SelCallbackRegByQuaVo;
import com.hxoms.modules.publicity.docCallback.entity.parameterEntity.SelCanCallbApplyVO;

import java.util.List;

public interface OmsPubDoccallbackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_pub_doccallback
     *
     * @mbg.generated Mon Jul 13 15:32:49 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_pub_doccallback
     *
     * @mbg.generated Mon Jul 13 15:32:49 CST 2020
     */
    int insert(OmsPubDoccallback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_pub_doccallback
     *
     * @mbg.generated Mon Jul 13 15:32:49 CST 2020
     */
    int insertSelective(OmsPubDoccallback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_pub_doccallback
     *
     * @mbg.generated Mon Jul 13 15:32:49 CST 2020
     */
    OmsPubDoccallback selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_pub_doccallback
     *
     * @mbg.generated Mon Jul 13 15:32:49 CST 2020
     */
    int updateByPrimaryKeySelective(OmsPubDoccallback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_pub_doccallback
     *
     * @mbg.generated Mon Jul 13 15:32:49 CST 2020
     */
    int updateByPrimaryKey(OmsPubDoccallback record);
    /**
     * @Desc: 查询可回收登记备案申请
     * @Author: wangyunquan
     * @Param: [id]
     * @Return: java.util.List<com.hxoms.modules.publicity.docCallback.entity.parameterEntity.SelCanCallbApplyVO>
     * @Date: 2020/7/7
     */
    List<SelCanCallbApplyVO> selectCanCallbApplyAll(String id);

    /**
     * @Desc: 查询批件回收登记记录
     * @Author: wangyunquan
     * @Param: [selCallbackRegByQuaVo]
     * @Return: java.util.List<com.hxoms.modules.publicity.docCallback.entity.OmsPubDocCallback>
     * @Date: 2020/7/7
     */
    List<OmsPubDoccallback> SelCallbackRegByQuaVoAll(SelCallbackRegByQuaVo selCallbackRegByQuaVo);

}