package com.hxoms.modules.publicity.docCallback.mapper;

import com.hxoms.modules.publicity.docCallback.entity.OmsPubDoccallbackdetail;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OmsPubDoccallbackdetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_pub_doccallbackdetail
     *
     * @mbg.generated Tue Jul 07 15:51:11 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_pub_doccallbackdetail
     *
     * @mbg.generated Tue Jul 07 15:51:11 CST 2020
     */
    int insert(OmsPubDoccallbackdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_pub_doccallbackdetail
     *
     * @mbg.generated Tue Jul 07 15:51:11 CST 2020
     */
    int insertSelective(OmsPubDoccallbackdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_pub_doccallbackdetail
     *
     * @mbg.generated Tue Jul 07 15:51:11 CST 2020
     */
    OmsPubDoccallbackdetail selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_pub_doccallbackdetail
     *
     * @mbg.generated Tue Jul 07 15:51:11 CST 2020
     */
    int updateByPrimaryKeySelective(OmsPubDoccallbackdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_pub_doccallbackdetail
     *
     * @mbg.generated Tue Jul 07 15:51:11 CST 2020
     */
    int updateByPrimaryKey(OmsPubDoccallbackdetail record);
    /**
     * @Desc: 批量插入批件回收登记明细
     * @Author: wangyunquan
     * @Param: [omsPubDestroydetailList]
     * @Return: int
     * @Date: 2020/7/7
     */
    int insertOmsPubDoccallbackdetailList(@Param("omsPubDoccallbackdetailList") List<OmsPubDoccallbackdetail> omsPubDoccallbackdetailList);

    /**
     * @Desc: 根据团组备案申请主键获取回收明细
     * @Author: gaozhenyuan
     * @Param: id
     * @Return: List<OmsPubDestroydetail>
     * @Date: 2020/8/21
     */
    List<OmsPubDoccallbackdetail> getPubDoccallbackdetailByYspId(String id);
}