package com.hxoms.modules.omsoperator.mapper;

import com.hxoms.modules.omsoperator.entity.A02;

public interface A02Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a02
     *
     * @mbg.generated Sun Sep 27 19:53:09 CST 2020
     */
    int deleteByPrimaryKey(String a0200);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a02
     *
     * @mbg.generated Sun Sep 27 19:53:09 CST 2020
     */
    int insert(A02 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a02
     *
     * @mbg.generated Sun Sep 27 19:53:09 CST 2020
     */
    int insertSelective(A02 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a02
     *
     * @mbg.generated Sun Sep 27 19:53:09 CST 2020
     */
    A02 selectByPrimaryKey(String a0200);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a02
     *
     * @mbg.generated Sun Sep 27 19:53:09 CST 2020
     */
    int updateByPrimaryKeySelective(A02 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a02
     *
     * @mbg.generated Sun Sep 27 19:53:09 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(A02 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a02
     *
     * @mbg.generated Sun Sep 27 19:53:09 CST 2020
     */
    int updateByPrimaryKey(A02 record);
}