package com.hxoms.modules.omsoperator.mapper;

import com.hxoms.modules.omsoperator.entity.A06;

public interface A06Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a06
     *
     * @mbg.generated Sun Sep 27 19:58:04 CST 2020
     */
    int deleteByPrimaryKey(String a0600);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a06
     *
     * @mbg.generated Sun Sep 27 19:58:04 CST 2020
     */
    int insert(A06 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a06
     *
     * @mbg.generated Sun Sep 27 19:58:04 CST 2020
     */
    int insertSelective(A06 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a06
     *
     * @mbg.generated Sun Sep 27 19:58:04 CST 2020
     */
    A06 selectByPrimaryKey(String a0600);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a06
     *
     * @mbg.generated Sun Sep 27 19:58:04 CST 2020
     */
    int updateByPrimaryKeySelective(A06 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a06
     *
     * @mbg.generated Sun Sep 27 19:58:04 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(A06 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a06
     *
     * @mbg.generated Sun Sep 27 19:58:04 CST 2020
     */
    int updateByPrimaryKey(A06 record);
}