package com.hxoms.modules.omsoperator.mapper;

import com.hxoms.modules.omsoperator.entity.A0809;

public interface A0809Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a0809
     *
     * @mbg.generated Sun Sep 27 19:58:45 CST 2020
     */
    int deleteByPrimaryKey(String a080900);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a0809
     *
     * @mbg.generated Sun Sep 27 19:58:45 CST 2020
     */
    int insert(A0809 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a0809
     *
     * @mbg.generated Sun Sep 27 19:58:45 CST 2020
     */
    int insertSelective(A0809 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a0809
     *
     * @mbg.generated Sun Sep 27 19:58:45 CST 2020
     */
    A0809 selectByPrimaryKey(String a080900);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a0809
     *
     * @mbg.generated Sun Sep 27 19:58:45 CST 2020
     */
    int updateByPrimaryKeySelective(A0809 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a0809
     *
     * @mbg.generated Sun Sep 27 19:58:45 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(A0809 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a0809
     *
     * @mbg.generated Sun Sep 27 19:58:45 CST 2020
     */
    int updateByPrimaryKey(A0809 record);
}