package com.hxoms.modules.omsoperator.mapper;


import com.hxoms.modules.omsoperator.entity.SysAttachment;

public interface SysAttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_attachment
     *
     * @mbg.generated Sun Sep 27 19:27:49 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_attachment
     *
     * @mbg.generated Sun Sep 27 19:27:49 CST 2020
     */
    int insert(SysAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_attachment
     *
     * @mbg.generated Sun Sep 27 19:27:49 CST 2020
     */
    int insertSelective(SysAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_attachment
     *
     * @mbg.generated Sun Sep 27 19:27:49 CST 2020
     */
    SysAttachment selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_attachment
     *
     * @mbg.generated Sun Sep 27 19:27:49 CST 2020
     */
    int updateByPrimaryKeySelective(SysAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_attachment
     *
     * @mbg.generated Sun Sep 27 19:27:49 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(SysAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_attachment
     *
     * @mbg.generated Sun Sep 27 19:27:49 CST 2020
     */
    int updateByPrimaryKey(SysAttachment record);
}