package com.hxoms.modules.passportCard.printGetQrCode.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.hxoms.modules.passportCard.printGetQrCode.entity.OmsCerPrintQrCode;
import com.hxoms.modules.passportCard.printGetQrCode.entity.parameterEntity.CanGetCerInfo;

import java.util.List;

public interface OmsCerPrintQrCodeMapper extends BaseMapper<OmsCerPrintQrCode> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cer_print_qr_code
     *
     * @mbg.generated Fri Aug 21 09:21:29 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cer_print_qr_code
     *
     * @mbg.generated Fri Aug 21 09:21:29 CST 2020
     */
    int insert(OmsCerPrintQrCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cer_print_qr_code
     *
     * @mbg.generated Fri Aug 21 09:21:29 CST 2020
     */
    int insertSelective(OmsCerPrintQrCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cer_print_qr_code
     *
     * @mbg.generated Fri Aug 21 09:21:29 CST 2020
     */
    OmsCerPrintQrCode selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cer_print_qr_code
     *
     * @mbg.generated Fri Aug 21 09:21:29 CST 2020
     */
    int updateByPrimaryKeySelective(OmsCerPrintQrCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cer_print_qr_code
     *
     * @mbg.generated Fri Aug 21 09:21:29 CST 2020
     */
    int updateByPrimaryKey(OmsCerPrintQrCode record);

    /**
     * @Desc: 查询可领取证照
     * @Author: wangyunquan
     * @Param: [id, overFlag]
     * @Return: java.util.List<com.hxoms.modules.passportCard.printGetQrCode.entity.parameterEntity.CanGetCerInfo>
     * @Date: 2020/8/20
     */
    List<CanGetCerInfo> selectCanGetCer(String id, String overFlag);
}