package com.hxoms.modules.roster.mapper;

import com.hxoms.modules.roster.entity.SysRegister;

import java.util.List;

public interface SysRegisterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_register
     *
     * @mbg.generated Fri Jul 10 12:02:49 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_register
     *
     * @mbg.generated Fri Jul 10 12:02:49 CST 2020
     */
    int insert(SysRegister record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_register
     *
     * @mbg.generated Fri Jul 10 12:02:49 CST 2020
     */
    int insertSelective(SysRegister record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_register
     *
     * @mbg.generated Fri Jul 10 12:02:49 CST 2020
     */
    SysRegister selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_register
     *
     * @mbg.generated Fri Jul 10 12:02:49 CST 2020
     */
    int updateByPrimaryKeySelective(SysRegister record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_register
     *
     * @mbg.generated Fri Jul 10 12:02:49 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(SysRegister record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_register
     *
     * @mbg.generated Fri Jul 10 12:02:49 CST 2020
     */
    int updateByPrimaryKey(SysRegister record);

    List<SysRegister> selectSysRegisterList(String pid);

}