package com.hxoms.modules.roster.mapper;

import com.hxoms.modules.roster.entity.SysRoster;

public interface SysRosterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roster
     *
     * @mbg.generated Fri Jul 10 12:03:14 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roster
     *
     * @mbg.generated Fri Jul 10 12:03:14 CST 2020
     */
    int insert(SysRoster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roster
     *
     * @mbg.generated Fri Jul 10 12:03:14 CST 2020
     */
    int insertSelective(SysRoster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roster
     *
     * @mbg.generated Fri Jul 10 12:03:14 CST 2020
     */
    SysRoster selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roster
     *
     * @mbg.generated Fri Jul 10 12:03:14 CST 2020
     */
    int updateByPrimaryKeySelective(SysRoster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roster
     *
     * @mbg.generated Fri Jul 10 12:03:14 CST 2020
     */
    int updateByPrimaryKey(SysRoster record);

    SysRoster selectSysRosterRtype(String rtype);
}