package com.hxoms.modules.passportCard.admintorGet.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.hxoms.modules.passportCard.admintorGet.entity.OmsCerAdmintorGetApply;
import com.hxoms.modules.passportCard.admintorGet.entity.parameterEntiry.AdmintorGetCerInfo;
import com.hxoms.modules.passportCard.admintorGet.entity.parameterEntiry.AdmintorGetQueryParam;

import java.util.List;

public interface OmsCerAdmintorGetApplyMapper extends BaseMapper<OmsCerAdmintorGetApply> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cer_admintor_get_apply
     *
     * @mbg.generated Tue Aug 18 15:44:52 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cer_admintor_get_apply
     *
     * @mbg.generated Tue Aug 18 15:44:52 CST 2020
     */
    int insert(OmsCerAdmintorGetApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cer_admintor_get_apply
     *
     * @mbg.generated Tue Aug 18 15:44:52 CST 2020
     */
    int insertSelective(OmsCerAdmintorGetApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cer_admintor_get_apply
     *
     * @mbg.generated Tue Aug 18 15:44:52 CST 2020
     */
    OmsCerAdmintorGetApply selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cer_admintor_get_apply
     *
     * @mbg.generated Tue Aug 18 15:44:52 CST 2020
     */
    int updateByPrimaryKeySelective(OmsCerAdmintorGetApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cer_admintor_get_apply
     *
     * @mbg.generated Tue Aug 18 15:44:52 CST 2020
     */
    int updateByPrimaryKey(OmsCerAdmintorGetApply record);

    /**
     * @Desc: 查询证照信息
     * @Author: wangyunquan
     * @Param: [admintorGetQueryParam]
     * @Return: java.util.List<com.hxoms.modules.passportCard.admintorGet.entity.parameterEntiry.AdmintorGetCerInfo>
     * @Date: 2020/8/18
     */
    List<AdmintorGetCerInfo> selectCerInfo(AdmintorGetQueryParam admintorGetQueryParam);
}