package com.hxoms.modules.passportCard.initialise.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.hxoms.modules.passportCard.initialise.entity.OmsCerExitEntryImportManage;

public interface OmsCerExitEntryImportManageMapper extends BaseMapper<OmsCerExitEntryImportManage> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cer_exit_entry_import_manage
     *
     * @mbg.generated Wed Aug 26 11:40:52 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cer_exit_entry_import_manage
     *
     * @mbg.generated Wed Aug 26 11:40:52 CST 2020
     */
    int insert(OmsCerExitEntryImportManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cer_exit_entry_import_manage
     *
     * @mbg.generated Wed Aug 26 11:40:52 CST 2020
     */
    int insertSelective(OmsCerExitEntryImportManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cer_exit_entry_import_manage
     *
     * @mbg.generated Wed Aug 26 11:40:52 CST 2020
     */
    OmsCerExitEntryImportManage selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cer_exit_entry_import_manage
     *
     * @mbg.generated Wed Aug 26 11:40:52 CST 2020
     */
    int updateByPrimaryKeySelective(OmsCerExitEntryImportManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cer_exit_entry_import_manage
     *
     * @mbg.generated Wed Aug 26 11:40:52 CST 2020
     */
    int updateByPrimaryKey(OmsCerExitEntryImportManage record);
}