package com.hxoms.modules.passportCard.initialise.mapper;

import com.hxoms.modules.passportCard.initialise.entity.OmsCerIssuePerson;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OmsCerIssuePersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cer_issue_person
     *
     * @mbg.generated Tue Jul 28 10:36:22 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cer_issue_person
     *
     * @mbg.generated Tue Jul 28 10:36:22 CST 2020
     */
    int insert(OmsCerIssuePerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cer_issue_person
     *
     * @mbg.generated Tue Jul 28 10:36:22 CST 2020
     */
    int insertSelective(OmsCerIssuePerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cer_issue_person
     *
     * @mbg.generated Tue Jul 28 10:36:22 CST 2020
     */
    OmsCerIssuePerson selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cer_issue_person
     *
     * @mbg.generated Tue Jul 28 10:36:22 CST 2020
     */
    int updateByPrimaryKeySelective(OmsCerIssuePerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cer_issue_person
     *
     * @mbg.generated Tue Jul 28 10:36:22 CST 2020
     */
    int updateByPrimaryKey(OmsCerIssuePerson record);

    int batchSaveEntity(@Param("omsCerIssuePersonList") List<OmsCerIssuePerson> omsCerIssuePersonList);

    int selectByEntity(OmsCerIssuePerson omsCerIssuePerson);
}