package com.hxoms.modules.passportCard.initialise.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.hxoms.modules.passportCard.initialise.entity.OmsCerImportBatch;

public interface OmsCerImportBatchMapper extends BaseMapper<OmsCerImportBatch> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cer_import_batch
     *
     * @mbg.generated Wed Aug 26 11:39:37 CST 2020
     */
    int deleteByPrimaryKey(String batchNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cer_import_batch
     *
     * @mbg.generated Wed Aug 26 11:39:37 CST 2020
     */
    int insert(OmsCerImportBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cer_import_batch
     *
     * @mbg.generated Wed Aug 26 11:39:37 CST 2020
     */
    int insertSelective(OmsCerImportBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cer_import_batch
     *
     * @mbg.generated Wed Aug 26 11:39:37 CST 2020
     */
    OmsCerImportBatch selectByPrimaryKey(String batchNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cer_import_batch
     *
     * @mbg.generated Wed Aug 26 11:39:37 CST 2020
     */
    int updateByPrimaryKeySelective(OmsCerImportBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cer_import_batch
     *
     * @mbg.generated Wed Aug 26 11:39:37 CST 2020
     */
    int updateByPrimaryKey(OmsCerImportBatch record);
}