package com.hxoms.modules.passportCard.initialise.mapper;

import com.hxoms.modules.passportCard.initialise.entity.OmsCerConuterNumber;

public interface OmsCerConuterNumberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cer_conuter_number
     *
     * @mbg.generated Tue Aug 25 14:44:59 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cer_conuter_number
     *
     * @mbg.generated Tue Aug 25 14:44:59 CST 2020
     */
    int insert(OmsCerConuterNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cer_conuter_number
     *
     * @mbg.generated Tue Aug 25 14:44:59 CST 2020
     */
    int insertSelective(OmsCerConuterNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cer_conuter_number
     *
     * @mbg.generated Tue Aug 25 14:44:59 CST 2020
     */
    OmsCerConuterNumber selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cer_conuter_number
     *
     * @mbg.generated Tue Aug 25 14:44:59 CST 2020
     */
    int updateByPrimaryKeySelective(OmsCerConuterNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cer_conuter_number
     *
     * @mbg.generated Tue Aug 25 14:44:59 CST 2020
     */
    int updateByPrimaryKey(OmsCerConuterNumber record);
}