package com.hxoms.modules.publicity.destroyReg.mapper;

import com.hxoms.modules.publicity.destroyReg.entity.OmsPubDestroy;
import com.hxoms.modules.publicity.destroyReg.entity.parameterEntity.SelDestroyApplyVO;
import com.hxoms.modules.publicity.destroyReg.entity.parameterEntity.SelDestroyRegByQuaVo;

import java.util.List;

public interface OmsPubDestroyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_pub_destroy
     *
     * @mbg.generated Mon Jul 13 14:22:49 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_pub_destroy
     *
     * @mbg.generated Mon Jul 13 14:22:49 CST 2020
     */
    int insert(OmsPubDestroy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_pub_destroy
     *
     * @mbg.generated Mon Jul 13 14:22:49 CST 2020
     */
    int insertSelective(OmsPubDestroy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_pub_destroy
     *
     * @mbg.generated Mon Jul 13 14:22:49 CST 2020
     */
    OmsPubDestroy selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_pub_destroy
     *
     * @mbg.generated Mon Jul 13 14:22:49 CST 2020
     */
    int updateByPrimaryKeySelective(OmsPubDestroy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_pub_destroy
     *
     * @mbg.generated Mon Jul 13 14:22:49 CST 2020
     */
    int updateByPrimaryKey(OmsPubDestroy record);
    /**
     * @Desc: 查询提交撤销备案申请
     * @Author: wangyunquan
     * @Param:
     * @Return:
     * @Date: 2020/7/2
     */
    List<SelDestroyApplyVO> selectSubmitDesApplyAll(String id);
    /**
     * @Desc: 查询已销毁登记记录
     * @Author: wangyunquan
     * @Param: [selDestroyRegByQuaVo]
     * @Return: java.util.List<com.hxoms.modules.publicity.destroyReg.entity.OmsPubDestroy>
     * @Date: 2020/7/2
     */
    List<OmsPubDestroy> SelDestroyRegByQuaVoAll(SelDestroyRegByQuaVo selDestroyRegByQuaVo);
}