package com.hxoms.modules.omsregcadre.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.hxoms.modules.omsregcadre.entity.OmsRegYearcheckInfo;

public interface OmsRegYearcheckInfoMapper extends BaseMapper<OmsRegYearcheckInfo> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_reg_yearcheckinfo
     *
     * @mbg.generated Mon May 11 16:49:14 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_reg_yearcheckinfo
     *
     * @mbg.generated Mon May 11 16:49:14 CST 2020
     */
    int insert(OmsRegYearcheckInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_reg_yearcheckinfo
     *
     * @mbg.generated Mon May 11 16:49:14 CST 2020
     */
    int insertSelective(OmsRegYearcheckInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_reg_yearcheckinfo
     *
     * @mbg.generated Mon May 11 16:49:14 CST 2020
     */
    OmsRegYearcheckInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_reg_yearcheckinfo
     *
     * @mbg.generated Mon May 11 16:49:14 CST 2020
     */
    int updateByPrimaryKeySelective(OmsRegYearcheckInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_reg_yearcheckinfo
     *
     * @mbg.generated Mon May 11 16:49:14 CST 2020
     */
    int updateByPrimaryKey(OmsRegYearcheckInfo record);
}