package com.hxoms.modules.passportCard.mapper;

import com.hxoms.modules.passportCard.entity.CfCertificateCollection;

public interface CfCertificateCollectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_certificate_collection
     *
     * @mbg.generated Tue Jun 02 08:45:11 CST 2020
     */
    int insert(CfCertificateCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_certificate_collection
     *
     * @mbg.generated Tue Jun 02 08:45:11 CST 2020
     */
    int insertSelective(CfCertificateCollection record);
}