package com.hxoms.modules.passportCard.counterGet.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.hxoms.modules.passportCard.counterGet.entity.OmsCerGetTask;
import com.hxoms.modules.passportCard.counterGet.entity.parameterEntity.CerGetTaskInfo;
import com.hxoms.modules.passportCard.counterGet.entity.parameterEntity.CerGetTaskQueryParam;
import com.hxoms.modules.passportCard.counterGet.entity.parameterEntity.IdentityParam;
import com.hxoms.modules.sysUser.entity.CfUser;

import java.util.List;

public interface OmsCerGetTaskMapper extends BaseMapper<OmsCerGetTask> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cer_get_task
     *
     * @mbg.generated Fri Aug 14 09:43:54 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cer_get_task
     *
     * @mbg.generated Fri Aug 14 09:43:54 CST 2020
     */
    int insert(OmsCerGetTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cer_get_task
     *
     * @mbg.generated Fri Aug 14 09:43:54 CST 2020
     */
    int insertSelective(OmsCerGetTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cer_get_task
     *
     * @mbg.generated Fri Aug 14 09:43:54 CST 2020
     */
    OmsCerGetTask selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cer_get_task
     *
     * @mbg.generated Fri Aug 14 09:43:54 CST 2020
     */
    int updateByPrimaryKeySelective(OmsCerGetTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cer_get_task
     *
     * @mbg.generated Fri Aug 14 09:43:54 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(OmsCerGetTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cer_get_task
     *
     * @mbg.generated Fri Aug 14 09:43:54 CST 2020
     */
    int updateByPrimaryKey(OmsCerGetTask record);

    /**
     * @Desc: 查询用户
     * @Author: wangyunquan
     * @Param: [identityParam]
     * @Return: java.util.List<com.hxoms.modules.sysUser.entity.CfUser>
     * @Date: 2020/8/14
     */
    List<CfUser> selectUserByQua(IdentityParam identityParam);

    /**
     * @Desc: 查询可领取证照
     * @Author: wangyunquan
     * @Param: [cerGetTaskQueryParam]
     * @Return: java.util.List<com.hxoms.modules.passportCard.counterGet.entity.parameterEntity.CerGetTaskInfo>
     * @Date: 2020/8/18
     */
    List<CerGetTaskInfo> selectCanGetCer(CerGetTaskQueryParam cerGetTaskQueryParam);

    /**
     * @Desc: 查询二维码URL是否存在
     * @Author: wangyunquan
     * @Param: [qRCode]
     * @Return: java.lang.String
     * @Date: 2020/9/7
     */
    String selectQRCode(String qRCode);

    /**
     * @Desc: 查询用户是否存在
     * @Author: wangyunquan
     * @Param: [cerGetTaskQueryParam]
     * @Return: java.lang.String
     * @Date: 2020/9/8
     */
    String selectUserIsExist(CerGetTaskQueryParam cerGetTaskQueryParam);

    /**
     * @description:根据业务主键删除取证任务
     * @author:杨波
     * @date:2020-10-21
     *  * @param ids
     * @return:
     **/
    void deleteTaskByBusinessId(String businessId);
}